apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld-exporter
  namespace: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqld-exporter
  template:
    metadata:
      labels:
        app: mysqld-exporter
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.17.2
        imagePullPolicy: IfNotPresent
        env:
        - name: DATA_SOURCE_NAME
          value: "monitor_user:ysh@mysql.tiktok.svc.cluster.local:3306/tiktok"
        ports:
        - containerPort: 9104
---
apiVersion: v1
kind: Service
metadata:
  name: mysqld-exporter
  namespace: tiktok
spec:
  selector:
    app: mysqld-exporter
  ports:
  - port: 9104
    targetPort: 9104
    protocol: TCP

