apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: tiktok
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets:
              - node-exporter.tiktok.svc.cluster.local:9100
      - job_name: 'mysql'
        static_configs:
          - targets:
              - telegraf.tiktok.svc.cluster.local:9273
      - job_name: 'minio'
        metrics_path: /minio/v2/metrics/cluster
        scheme: http
        static_configs:
          - targets:
              - minio.tiktok.svc.cluster.local:9000
      - job_name: 'user-service'
        static_configs:
          - targets: 
              - user-service.tiktok.svc.cluster.local:18081
