// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"ralation-service/internal/biz"
	"ralation-service/internal/conf"
	"ralation-service/internal/data"
	"ralation-service/internal/server"
	"ralation-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry, elasticsearch *conf.Elasticsearch) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	typedClient, err := data.NewEsClient(elasticsearch)
	if err != nil {
		return nil, nil, err
	}
	discovery := data.NewDiscover(registry)
	userServiceClient := data.UserClient(confData, discovery)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, typedClient, elasticsearch, userServiceClient)
	if err != nil {
		return nil, nil, err
	}
	relationRepo := data.NewRelationRepo(dataData, logger)
	relationUsecase := biz.NewGreeterUsecase(relationRepo, logger)
	relationService := service.NewRelationService(relationUsecase)
	grpcServer := server.NewGRPCServer(confServer, relationService, logger)
	httpServer := server.NewHTTPServer(confServer, relationService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
