// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"comment-service/internal/biz"
	"comment-service/internal/conf"
	"comment-service/internal/data"
	"comment-service/internal/pkg"
	"comment-service/internal/server"
	"comment-service/internal/service"
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *consul.Registry, idGen *conf.IDGen) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	idGenerator := pkg.NewIDGen(idGen)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, registry, idGenerator)
	if err != nil {
		return nil, nil, err
	}
	commentRepo := data.NewCommentRepo(dataData, logger)
	commentUsecase := biz.NewCommentUsecase(commentRepo, logger)
	commentService := service.NewCommentService(commentUsecase)
	grpcServer := server.NewGRPCServer(confServer, commentService, logger)
	httpServer := server.NewHTTPServer(confServer, commentService, logger)
	app := newApp(logger, grpcServer, httpServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
