apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: tiktok
spec:
  selector:
    app: kafka
  ports:
    - name: broker
      port: 19092
      targetPort: 19092
    - name: controller
      port: 9093
      targetPort: 9093

