apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  namespace: tiktok
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
  namespace: tiktok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

