// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"video-service/internal/biz"
	"video-service/internal/conf"
	"video-service/internal/data"
	"video-service/internal/pkg"
	"video-service/internal/server"
	"video-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, jwt *conf.JWT, data_MinIO *conf.Data_MinIO, idGen *conf.IDGen, registry *consul.Registry) (*kratos.App, func(), error) {
	jwtManager := pkg.NewJWTManagerProvider(jwt)
	minioUploader := pkg.NewMinioUploaderProvider(data_MinIO)
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	idGenerator := pkg.NewIDGenerator(idGen)
	dataData, cleanup, err := data.NewData(confData, logger, jwtManager, minioUploader, db, client, idGenerator, registry)
	if err != nil {
		return nil, nil, err
	}
	videoRepo := data.NewVideoRepo(dataData, logger)
	videoUsecase := biz.NewVideoUsecase(videoRepo, logger)
	videoService := service.NewVideoService(videoUsecase)
	grpcServer := server.NewGRPCServer(confServer, videoService, logger)
	httpServer := server.NewHTTPServer(confServer, videoService, logger)
	app, cleanup2, err := newAppWithService(logger, grpcServer, httpServer, videoService, registry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
