apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tiktok
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30306  # 你可以改成别的端口，只要在 30000~32767 范围内

