server:
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9081
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(mysql:3306)/tiktok?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
jwt:
  secret: "youngking98" 
  issuer: "user-service"
  expire: 86400
idGen:
  machine_id: 1
  start_time: "2025-01-01T00:00:00Z"
registry:
  consul:
    addr: consul-server:8500
    scheme: http
  advertise:
    addr: user-service-test:9081
service:
  name: user-service
  version: v1.0.0
log:
  level: debug
  path: ../logs/app.log
  max_size: 100
  max_backups: 5
  max_age: 3
  compress: true
  console: true
open_telemetry:
  endpoint: "jaeger:4317"