// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: favorite/v1/favorite.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FavoriteActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	VideoId       int64                  `protobuf:"varint,3,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"` // 1：点赞， 2： 取消
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionRequest) Reset() {
	*x = FavoriteActionRequest{}
	mi := &file_favorite_v1_favorite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionRequest) ProtoMessage() {}

func (x *FavoriteActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_v1_favorite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionRequest.ProtoReflect.Descriptor instead.
func (*FavoriteActionRequest) Descriptor() ([]byte, []int) {
	return file_favorite_v1_favorite_proto_rawDescGZIP(), []int{0}
}

func (x *FavoriteActionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *FavoriteActionRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *FavoriteActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *FavoriteActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type FavoriteActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteActionReply) Reset() {
	*x = FavoriteActionReply{}
	mi := &file_favorite_v1_favorite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteActionReply) ProtoMessage() {}

func (x *FavoriteActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_v1_favorite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteActionReply.ProtoReflect.Descriptor instead.
func (*FavoriteActionReply) Descriptor() ([]byte, []int) {
	return file_favorite_v1_favorite_proto_rawDescGZIP(), []int{1}
}

func (x *FavoriteActionReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserFavoriteVideoListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId  int64                  `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFavoriteVideoListRequest) Reset() {
	*x = GetUserFavoriteVideoListRequest{}
	mi := &file_favorite_v1_favorite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFavoriteVideoListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFavoriteVideoListRequest) ProtoMessage() {}

func (x *GetUserFavoriteVideoListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_v1_favorite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFavoriteVideoListRequest.ProtoReflect.Descriptor instead.
func (*GetUserFavoriteVideoListRequest) Descriptor() ([]byte, []int) {
	return file_favorite_v1_favorite_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserFavoriteVideoListRequest) GetTargetUserId() int64 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *GetUserFavoriteVideoListRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetUserFavoriteVideoListRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GetUserFavoriteVideoListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserFavoriteVideoListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserFavoriteVideoListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFavoriteVideoListReply) Reset() {
	*x = GetUserFavoriteVideoListReply{}
	mi := &file_favorite_v1_favorite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFavoriteVideoListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFavoriteVideoListReply) ProtoMessage() {}

func (x *GetUserFavoriteVideoListReply) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_v1_favorite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFavoriteVideoListReply.ProtoReflect.Descriptor instead.
func (*GetUserFavoriteVideoListReply) Descriptor() ([]byte, []int) {
	return file_favorite_v1_favorite_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserFavoriteVideoListReply) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverUrl      string                 `protobuf:"bytes,3,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	LikeCount     int64                  `protobuf:"varint,5,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,6,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	PublishTime   int64                  `protobuf:"varint,7,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_favorite_v1_favorite_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_favorite_v1_favorite_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_favorite_v1_favorite_proto_rawDescGZIP(), []int{4}
}

func (x *Video) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Video) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetPublishTime() int64 {
	if x != nil {
		return x.PublishTime
	}
	return 0
}

var File_favorite_v1_favorite_proto protoreflect.FileDescriptor

const file_favorite_v1_favorite_proto_rawDesc = "" +
	"\n" +
	"\x1afavorite/v1/favorite.proto\x12\bfavorite\x1a\x1cgoogle/api/annotations.proto\"\x8d\x01\n" +
	"\x15FavoriteActionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12\x19\n" +
	"\bvideo_id\x18\x03 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\x05R\n" +
	"actionType\"/\n" +
	"\x13FavoriteActionReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xac\x01\n" +
	"\x1fGetUserFavoriteVideoListRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\x03R\ftargetUserId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"H\n" +
	"\x1dGetUserFavoriteVideoListReply\x12'\n" +
	"\x06videos\x18\x01 \x03(\v2\x0f.favorite.VideoR\x06videos\"\xd9\x01\n" +
	"\x05Video\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tcover_url\x18\x03 \x01(\tR\bcoverUrl\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1d\n" +
	"\n" +
	"like_count\x18\x05 \x01(\x03R\tlikeCount\x12#\n" +
	"\rcomment_count\x18\x06 \x01(\x03R\fcommentCount\x12!\n" +
	"\fpublish_time\x18\a \x01(\x03R\vpublishTime2\x93\x02\n" +
	"\x0fFavoriteService\x12q\n" +
	"\x0eFavoriteAction\x12\x1f.favorite.FavoriteActionRequest\x1a\x1d.favorite.FavoriteActionReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/favorite/action\x12\x8c\x01\n" +
	"\x18GetUserFavoriteVideoList\x12).favorite.GetUserFavoriteVideoListRequest\x1a'.favorite.GetUserFavoriteVideoListReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/favorite/videosB\x14Z\x12favorite/api/v1;v1b\x06proto3"

var (
	file_favorite_v1_favorite_proto_rawDescOnce sync.Once
	file_favorite_v1_favorite_proto_rawDescData []byte
)

func file_favorite_v1_favorite_proto_rawDescGZIP() []byte {
	file_favorite_v1_favorite_proto_rawDescOnce.Do(func() {
		file_favorite_v1_favorite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_favorite_v1_favorite_proto_rawDesc), len(file_favorite_v1_favorite_proto_rawDesc)))
	})
	return file_favorite_v1_favorite_proto_rawDescData
}

var file_favorite_v1_favorite_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_favorite_v1_favorite_proto_goTypes = []any{
	(*FavoriteActionRequest)(nil),           // 0: favorite.FavoriteActionRequest
	(*FavoriteActionReply)(nil),             // 1: favorite.FavoriteActionReply
	(*GetUserFavoriteVideoListRequest)(nil), // 2: favorite.GetUserFavoriteVideoListRequest
	(*GetUserFavoriteVideoListReply)(nil),   // 3: favorite.GetUserFavoriteVideoListReply
	(*Video)(nil),                           // 4: favorite.Video
}
var file_favorite_v1_favorite_proto_depIdxs = []int32{
	4, // 0: favorite.GetUserFavoriteVideoListReply.videos:type_name -> favorite.Video
	0, // 1: favorite.FavoriteService.FavoriteAction:input_type -> favorite.FavoriteActionRequest
	2, // 2: favorite.FavoriteService.GetUserFavoriteVideoList:input_type -> favorite.GetUserFavoriteVideoListRequest
	1, // 3: favorite.FavoriteService.FavoriteAction:output_type -> favorite.FavoriteActionReply
	3, // 4: favorite.FavoriteService.GetUserFavoriteVideoList:output_type -> favorite.GetUserFavoriteVideoListReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_favorite_v1_favorite_proto_init() }
func file_favorite_v1_favorite_proto_init() {
	if File_favorite_v1_favorite_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_favorite_v1_favorite_proto_rawDesc), len(file_favorite_v1_favorite_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_favorite_v1_favorite_proto_goTypes,
		DependencyIndexes: file_favorite_v1_favorite_proto_depIdxs,
		MessageInfos:      file_favorite_v1_favorite_proto_msgTypes,
	}.Build()
	File_favorite_v1_favorite_proto = out.File
	file_favorite_v1_favorite_proto_goTypes = nil
	file_favorite_v1_favorite_proto_depIdxs = nil
}
