// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID    int64     `gorm:"column:user_id;not null;comment:ID" json:"user_id"`            // ID
	VideoID   int64     `gorm:"column:video_id;not null;comment:ID" json:"video_id"`          // ID
	ParentID  int64     `gorm:"column:parent_id;comment:ID0" json:"parent_id"`                // ID0
	Content   string    `gorm:"column:content;not null" json:"content"`
	IsDeleted bool      `gorm:"column:is_deleted;not null;comment:0-1-" json:"is_deleted"` // 0-1-
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
