// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID              int64          `gorm:"column:id;primaryKey;comment:ID" json:"id"` // ID
	Username        string         `gorm:"column:username;not null" json:"username"`
	PasswordHash    string         `gorm:"column:password_hash;not null" json:"password_hash"`
	Avatar          string         `gorm:"column:avatar;comment:URL" json:"avatar"` // URL
	BackgroundImage string         `gorm:"column:background_image" json:"background_image"`
	Signature       string         `gorm:"column:signature" json:"signature"`
	FollowCount     int32          `gorm:"column:follow_count;not null" json:"follow_count"`
	FollowerCount   int32          `gorm:"column:follower_count;not null" json:"follower_count"`
	WorkCount       int32          `gorm:"column:work_count;not null" json:"work_count"`
	FavoriteCount   int32          `gorm:"column:favorite_count;not null" json:"favorite_count"`
	TotalFavorited  int32          `gorm:"column:total_favorited;not null" json:"total_favorited"`
	Tags            string         `gorm:"column:tags;comment:AI" json:"tags"`                        // AI
	Status          int32          `gorm:"column:status;not null;default:1;comment:10" json:"status"` // 10
	Extra           string         `gorm:"column:extra" json:"extra"`
	Reserved1       string         `gorm:"column:reserved1;comment:1" json:"reserved1"` // 1
	Reserved2       string         `gorm:"column:reserved2;comment:2" json:"reserved2"` // 2
	CreatedAt       time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
