// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameVideo = "videos"

// Video mapped from table <videos>
type Video struct {
	ID              int64     `gorm:"column:id;primaryKey;comment:IDID" json:"id"`       // IDID
	UserID          int64     `gorm:"column:user_id;not null;comment:ID" json:"user_id"` // ID
	PlayURL         string    `gorm:"column:play_url;not null" json:"play_url"`
	CoverURL        string    `gorm:"column:cover_url;not null" json:"cover_url"`
	Title           string    `gorm:"column:title;not null" json:"title"`
	Description     string    `gorm:"column:description" json:"description"`
	Duration        float32   `gorm:"column:duration" json:"duration"`
	Tags            string    `gorm:"column:tags" json:"tags"`
	FavoriteCnt     int32     `gorm:"column:favorite_cnt" json:"favorite_cnt"`
	CommentCnt      int32     `gorm:"column:comment_cnt" json:"comment_cnt"`
	ShareCnt        int32     `gorm:"column:share_cnt" json:"share_cnt"`
	CollectCnt      int32     `gorm:"column:collect_cnt" json:"collect_cnt"`
	IsPublic        bool      `gorm:"column:is_public;default:1;comment:01" json:"is_public"`        // 01
	AuditStatus     int32     `gorm:"column:audit_status;default:1;comment:012" json:"audit_status"` // 012
	IsOriginal      bool      `gorm:"column:is_original;default:1;comment:10" json:"is_original"`    // 10
	SourceURL       string    `gorm:"column:source_url" json:"source_url"`
	TranscodeStatus int32     `gorm:"column:transcode_status;default:1;comment:012" json:"transcode_status"` // 012
	VideoWidth      int32     `gorm:"column:video_width" json:"video_width"`
	VideoHeight     int32     `gorm:"column:video_height" json:"video_height"`
	BizExt          string    `gorm:"column:biz_ext" json:"biz_ext"`
	Reserved1       string    `gorm:"column:reserved_1;comment:1" json:"reserved_1"` // 1
	Reserved2       string    `gorm:"column:reserved_2;comment:2" json:"reserved_2"` // 2
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdateTime      time.Time `gorm:"column:update_time;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteAt        time.Time `gorm:"column:delete_at" json:"delete_at"`
}

// TableName Video's table name
func (*Video) TableName() string {
	return TableNameVideo
}
