// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: relation/v1/relation.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelationControlRequest 建立和删除关系操作
type RelationControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ToUserId      int64                  `protobuf:"varint,3,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	ActionType    int32                  `protobuf:"varint,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationControlRequest) Reset() {
	*x = RelationControlRequest{}
	mi := &file_relation_v1_relation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationControlRequest) ProtoMessage() {}

func (x *RelationControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationControlRequest.ProtoReflect.Descriptor instead.
func (*RelationControlRequest) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{0}
}

func (x *RelationControlRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RelationControlRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RelationControlRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *RelationControlRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type RelationControlReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationControlReply) Reset() {
	*x = RelationControlReply{}
	mi := &file_relation_v1_relation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationControlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationControlReply) ProtoMessage() {}

func (x *RelationControlReply) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationControlReply.ProtoReflect.Descriptor instead.
func (*RelationControlReply) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{1}
}

func (x *RelationControlReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// GetRelationListByUserID 根据用户id获取用户关注列表
type GetRelationListByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationListByUserIDRequest) Reset() {
	*x = GetRelationListByUserIDRequest{}
	mi := &file_relation_v1_relation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationListByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationListByUserIDRequest) ProtoMessage() {}

func (x *GetRelationListByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationListByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetRelationListByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{2}
}

func (x *GetRelationListByUserIDRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetRelationListByUserIDRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *GetRelationListByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRelationListByUserIDReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationListByUserIDReply) Reset() {
	*x = GetRelationListByUserIDReply{}
	mi := &file_relation_v1_relation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationListByUserIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationListByUserIDReply) ProtoMessage() {}

func (x *GetRelationListByUserIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationListByUserIDReply.ProtoReflect.Descriptor instead.
func (*GetRelationListByUserIDReply) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{3}
}

func (x *GetRelationListByUserIDReply) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // 用户id
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                              // 用户名称
	FollowCount     int32                  `protobuf:"varint,3,opt,name=follow_count,json=followCount,proto3" json:"follow_count,omitempty"`            // 关注总数
	FollowerCount   int32                  `protobuf:"varint,4,opt,name=follower_count,json=followerCount,proto3" json:"follower_count,omitempty"`      // 粉丝总数
	IsFollow        bool                   `protobuf:"varint,5,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`                     // true-已关注，false-未关注
	Avatar          string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`                                          // 用户头像
	BackgroundImage string                 `protobuf:"bytes,7,opt,name=background_image,json=backgroundImage,proto3" json:"background_image,omitempty"` // 用户个人页顶部大图
	Signature       string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`                                    // 个人简介
	TotalFavorited  int32                  `protobuf:"varint,9,opt,name=total_favorited,json=totalFavorited,proto3" json:"total_favorited,omitempty"`   // 获赞数量
	WorkCount       int32                  `protobuf:"varint,10,opt,name=work_count,json=workCount,proto3" json:"work_count,omitempty"`                 // 作品数量
	FavoriteCount   int32                  `protobuf:"varint,11,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"`     // 点赞数量
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_relation_v1_relation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_relation_v1_relation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_relation_v1_relation_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetFollowCount() int32 {
	if x != nil {
		return x.FollowCount
	}
	return 0
}

func (x *User) GetFollowerCount() int32 {
	if x != nil {
		return x.FollowerCount
	}
	return 0
}

func (x *User) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetBackgroundImage() string {
	if x != nil {
		return x.BackgroundImage
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetTotalFavorited() int32 {
	if x != nil {
		return x.TotalFavorited
	}
	return 0
}

func (x *User) GetWorkCount() int32 {
	if x != nil {
		return x.WorkCount
	}
	return 0
}

func (x *User) GetFavoriteCount() int32 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

var File_relation_v1_relation_proto protoreflect.FileDescriptor

const file_relation_v1_relation_proto_rawDesc = "" +
	"\n" +
	"\x1arelation/v1/relation.proto\x12\brelation\x1a\x1cgoogle/api/annotations.proto\"\x92\x01\n" +
	"\x16RelationControlRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x03 \x01(\x03R\btoUserId\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\x05R\n" +
	"actionType\"(\n" +
	"\x14RelationControlReply\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"t\n" +
	"\x1eGetRelationListByUserIDRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"B\n" +
	"\x1cGetRelationListByUserIDReply\x12\"\n" +
	"\x04user\x18\x01 \x03(\v2\x0e.relation.UserR\x04user\"\xe1\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\ffollow_count\x18\x03 \x01(\x05R\vfollowCount\x12%\n" +
	"\x0efollower_count\x18\x04 \x01(\x05R\rfollowerCount\x12\x1b\n" +
	"\tis_follow\x18\x05 \x01(\bR\bisFollow\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12)\n" +
	"\x10background_image\x18\a \x01(\tR\x0fbackgroundImage\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\x12'\n" +
	"\x0ftotal_favorited\x18\t \x01(\x05R\x0etotalFavorited\x12\x1d\n" +
	"\n" +
	"work_count\x18\n" +
	" \x01(\x05R\tworkCount\x12%\n" +
	"\x0efavorite_count\x18\v \x01(\x05R\rfavoriteCount2\x92\x02\n" +
	"\x0fRelationService\x12u\n" +
	"\x0fRelationControl\x12 .relation.RelationControlRequest\x1a\x1e.relation.RelationControlReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/relation/control\x12\x87\x01\n" +
	"\x17GetRelationListByUserID\x12(.relation.GetRelationListByUserIDRequest\x1a&.relation.GetRelationListByUserIDReply\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/relation/listB\x14Z\x12relation/api/v1;v1b\x06proto3"

var (
	file_relation_v1_relation_proto_rawDescOnce sync.Once
	file_relation_v1_relation_proto_rawDescData []byte
)

func file_relation_v1_relation_proto_rawDescGZIP() []byte {
	file_relation_v1_relation_proto_rawDescOnce.Do(func() {
		file_relation_v1_relation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relation_v1_relation_proto_rawDesc), len(file_relation_v1_relation_proto_rawDesc)))
	})
	return file_relation_v1_relation_proto_rawDescData
}

var file_relation_v1_relation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_relation_v1_relation_proto_goTypes = []any{
	(*RelationControlRequest)(nil),         // 0: relation.RelationControlRequest
	(*RelationControlReply)(nil),           // 1: relation.RelationControlReply
	(*GetRelationListByUserIDRequest)(nil), // 2: relation.GetRelationListByUserIDRequest
	(*GetRelationListByUserIDReply)(nil),   // 3: relation.GetRelationListByUserIDReply
	(*User)(nil),                           // 4: relation.User
}
var file_relation_v1_relation_proto_depIdxs = []int32{
	4, // 0: relation.GetRelationListByUserIDReply.user:type_name -> relation.User
	0, // 1: relation.RelationService.RelationControl:input_type -> relation.RelationControlRequest
	2, // 2: relation.RelationService.GetRelationListByUserID:input_type -> relation.GetRelationListByUserIDRequest
	1, // 3: relation.RelationService.RelationControl:output_type -> relation.RelationControlReply
	3, // 4: relation.RelationService.GetRelationListByUserID:output_type -> relation.GetRelationListByUserIDReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_relation_v1_relation_proto_init() }
func file_relation_v1_relation_proto_init() {
	if File_relation_v1_relation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relation_v1_relation_proto_rawDesc), len(file_relation_v1_relation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relation_v1_relation_proto_goTypes,
		DependencyIndexes: file_relation_v1_relation_proto_depIdxs,
		MessageInfos:      file_relation_v1_relation_proto_msgTypes,
	}.Build()
	File_relation_v1_relation_proto = out.File
	file_relation_v1_relation_proto_goTypes = nil
	file_relation_v1_relation_proto_depIdxs = nil
}
