apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
  namespace: tiktok
  labels:
    app: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - name: consul
        image: hashicorp/consul:1.18
        imagePullPolicy: IfNotPresent
        args:
          - "agent"
          - "-server"
          - "-ui"
          - "-bootstrap"
          - "-client=0.0.0.0"
        ports:
          - containerPort: 8500  # HTTP UI and API
          - containerPort: 8600  # DNS
          - containerPort: 8600
            protocol: UDP
        readinessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /v1/status/leader
            port: 8500
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: consul-server
  namespace: tiktok
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
    - name: dns-tcp
      port: 8600
      targetPort: 8600
      protocol: TCP
    - name: dns-udp
      port: 8600
      targetPort: 8600
      protocol: UDP
  type: ClusterIP

