// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user-service/internal/biz"
	"user-service/internal/conf"
	"user-service/internal/data"
	"user-service/internal/pkg"
	"user-service/internal/server"
	"user-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, jwt *conf.JWT, idGen *conf.IDGen, logger log.Logger, string2 string) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	jwtManager := pkg.NewJWTManagerProvider(jwt)
	idGenerator := pkg.NewIDGen(idGen)
	dataData, cleanup, err := data.NewData(db, logger, client, jwtManager, idGenerator)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userService := biz.NewUserService(userRepo, logger)
	userServiceService := service.NewUserServiceService(userService)
	grpcServer := server.NewGRPCServer(confServer, userServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, userServiceService, logger)
	app := newApp(logger, grpcServer, httpServer, string2)
	return app, func() {
		cleanup()
	}, nil
}
