// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.19.4
// source: feed/v1/feed.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFeedServiceGetFeed = "/feed.FeedService/GetFeed"

type FeedServiceHTTPServer interface {
	GetFeed(context.Context, *FeedRequest) (*FeedReply, error)
}

func RegisterFeedServiceHTTPServer(s *http.Server, srv FeedServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/feed", _FeedService_GetFeed0_HTTP_Handler(srv))
}

func _FeedService_GetFeed0_HTTP_Handler(srv FeedServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FeedRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFeedServiceGetFeed)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFeed(ctx, req.(*FeedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FeedReply)
		return ctx.Result(200, reply)
	}
}

type FeedServiceHTTPClient interface {
	GetFeed(ctx context.Context, req *FeedRequest, opts ...http.CallOption) (rsp *FeedReply, err error)
}

type FeedServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFeedServiceHTTPClient(client *http.Client) FeedServiceHTTPClient {
	return &FeedServiceHTTPClientImpl{client}
}

func (c *FeedServiceHTTPClientImpl) GetFeed(ctx context.Context, in *FeedRequest, opts ...http.CallOption) (*FeedReply, error) {
	var out FeedReply
	pattern := "/api/feed"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFeedServiceGetFeed))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
