apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
  namespace: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: comment-service
          image: youngking666/comment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
            - containerPort: 9084
          env:
            - name: VIDEO_SERVICE_HOST
              value: http://video-service.tiktok.svc.cluster.local
      initContainers:
        - name: wait-for-video
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z video-service.tiktok.svc.cluster.local 8082; do echo waiting for video-service; sleep 2; done']
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: tiktok
spec:
  selector:
    app: comment-service
  type: NodePort
  ports:
    - name: http-8084
      port: 8084
      targetPort: 8084
      nodePort: 30884
    - name: metrics-9084
      port: 9084
      targetPort: 9084

