apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-service
  namespace: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-service
  template:
    metadata:
      labels:
        app: feed-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: node1
      containers:
        - name: feed-service
          image: youngking666/feed-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
            - containerPort: 9085
          env:
            - name: VIDEO_SERVICE_HOST
              value: http://video-service.tiktok.svc.cluster.local
      initContainers:
        - name: wait-for-video
          image: busybox:1.35
          command: ['sh', '-c', 'until nc -z video-service.tiktok.svc.cluster.local 8082; do echo waitting for video-service; sleep 2; done'] 
---
apiVersion: v1
kind: Service
metadata:
  name: feed-service
  namespace: tiktok
spec:
  selector:
    app: feed-service
  type: NodePort
  ports:
    - name: http-8085
      port: 8085
      targetPort: 8085
      nodePort: 30885
    - name: grpc-9085
      port: 9085
      targetPort: 9085
