// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"feed-service/internal/biz"
	"feed-service/internal/conf"
	"feed-service/internal/data"
	"feed-service/internal/server"
	"feed-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *conf.Registry) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	discovery := data.NewDiscover(registry)
	userServiceClient := data.NewUserServiceClient(confData, discovery)
	videoServiceClient := data.NewVideoServiceClient(confData, discovery)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, userServiceClient, videoServiceClient)
	if err != nil {
		return nil, nil, err
	}
	feedRepo := data.NewFeedRepo(dataData, logger)
	feedUsecase := biz.NewFeedUsecase(feedRepo, logger)
	feedService := service.NewFeedService(feedUsecase)
	grpcServer := server.NewGRPCServer(confServer, feedService, logger)
	httpServer := server.NewHTTPServer(confServer, feedService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
