apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: tiktok
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.10
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch.tiktok.svc.cluster.local:9200"
            - name: XPACK_SECURITY_ENABLED
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: tiktok
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
  type: NodePort

