apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: tiktok
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
      targetPort: 5601
      nodePort: 31601  # 你可以根据需要换端口，30000-32767 范围内
  type: NodePort

