// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"favorite-service/internal/biz"
	"favorite-service/internal/conf"
	"favorite-service/internal/data"
	"favorite-service/internal/server"
	"favorite-service/internal/service"
	"github.com/go-kratos/kratos/contrib/registry/consul/v2"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger, registry *consul.Registry) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client := data.NewRedisClient(confData)
	dataData, cleanup, err := data.NewData(confData, logger, db, client, registry)
	if err != nil {
		return nil, nil, err
	}
	favoriteRepo := data.NewFavoriteRepo(dataData, logger)
	favoriteUsecase := biz.NewFavoriteUsecase(favoriteRepo, logger)
	favoriteService := service.NewFavoriteService(favoriteUsecase)
	grpcServer := server.NewGRPCServer(confServer, favoriteService, logger)
	httpServer := server.NewHTTPServer(confServer, favoriteService, logger)
	app := newApp(logger, grpcServer, httpServer, registry)
	return app, func() {
		cleanup()
	}, nil
}
