server:
  http:
    addr: 0.0.0.0:8086
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9086
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(mysql:3306)/tiktok?parseTime=True&loc=Local
  redis:
    addr: redis:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  user_service:
    endpoint: discovery:///user-service
registry:
  consul:
    addr: consul-server:8500
service:
  name: relation-service
  version: v1.0.0
elasticsearch:
  addresses:
    - "elasticsearch:9200"
  index: "tiktok_relation"
