server:
  http:
    addr: 0.0.0.0:8084
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9094
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/tiktok?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  user_service:
    endpoint: discovery:///user-service
  video_service:
    endpoint: discovery:///video-service
registry:
  consul:
    addr: 127.0.0.1:8500
service:
  name: comment-service
  version: v1.0.0
idGen:
  machine_id: 3
  start_time: "2025-01-01T00:00:00Z"